Create q4_spectaprod
dashincubator/proposals pull request #6
Opened 2022-10-10 14:32 UTC by spectaprod

QA proposal

2022-10-10 16:07 UTC, riongull requested changes
Please see in-line comments.  Let's get on the phone or Discord to discuss monthly budget in context of our overall budget request.

2022-10-11 14:45 UTC, spectaprod commented on internal/q4_spectaprod
> +* [Interactive Dash Ecosystem Webpage](https://trello.com/c/djmlrMDC) - This was an inherited bounty, and is nearing completion. This is closely related to the infographic (above). It is the "present
as far as the 2 I have (you have the 3rd), the difference is the infographic is the graphic and contents, the webpage is the in-browser display, zoom in/out functionality and language.

2022-10-11 14:46 UTC, spectaprod commented on internal/q4_spectaprod
> +* [Automations for platform-test-suite](https://trello.com/c/hBqUETkb) - **Completed** This bounty automated manual operations required to work with the platform test suite.
it turned out to only be the individual task (the .env automation). We had both anticipated more, but no.

2022-10-11 14:48 UTC, spectaprod commented on internal/q4_spectaprod
> +I am requesting 1000 DASH from the Incubator general budget.  This will cover the budget to fund the projects I'm administering directly, as well as continuing to build a reserve fund for launching/c
changed

2022-10-11 21:10 UTC, riongull commented on internal/q4_spectaprod
> +During the upcoming In that time I plan to focus on the above Bounties and additionally (depending on the status of Platform):
Still here after your last commit

2022-10-11 21:18 UTC, riongull requested changes
Just a couple issues remain before I can merge this.  
- One from above (last review)
- One below that I just made.

2022-10-11 21:18 UTC, riongull commented on internal/2022_q4_spectaprod
> +I am requesting 600 DASH from the Incubator general budget.  This will cover the budget to fund the projects I'm administering directly, continue continuing to build a reserve fund (currently stands
Please update this:
>  600 DASH from the Incubator general budget.
to 
> 200 DASH/month for 3 months.

Dash superblocks pay out monthly so I have to request a monthly amount, repeated for 3 months in our external Incubator proposal. I want internal proposals to mirror that, so request a monthly amount for the quarter.  Oh, and again, you're not requesting from the "Incubator general fund", so just leave that part out.

Also, please fix the "continue continuing" typo.

2022-10-12 16:41 UTC, merged